version: '3.8'
services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      TZ: 'Europe/Paris'
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

volumes:
  database_data:
